import { useEffect, useState } from 'react'
import cable from '../lib/cable.js'
import API_URL from '../lib/api.js'

const Notifications = () => {
    const [notifications, setNotifications] = useState([]);         // ActionCable func to set notifications into an array for loading
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    // Fetch any existing notifications
    const fetchNotification = async () => {
        try {
            const response = await fetch(`${API_URL}/notifications`, {
                method: 'GET',
                credentials: 'include',
                headers: {
                    'Accept': 'application/json'
                },
            });
            
            if (!response.ok) {
                throw new Error(`Error: ${response.status}`)
            }

            // attaches the retrieved data to a var named data
            const data = await response.json();
            setNotifications(data);
        } catch (err) {
            console.error('Error:', err);
            setError('Failed to load notifications for user');
        } finally {
            setLoading(false);
        }
    };

    // Subscribe to action cable after fetch
    // Fetches current notifications before subscribing for real time events
    useEffect(() => {
        fetchNotification();
        const subscription = cable.subscriptions.create(
            { channel: 'NotificationsChannel' },            // Connecting to rails Redis Notification Channel
            {
                // Using console to check for connection
                connected() {
                    console.log('Connected to Notifications Chanel');
                },
                disconnected() {
                    console.log('Disconnected from Notifications Channel');
                },
                received(data) {
                    console.log('New Notification:', data);
                    setNotifications((prev) => [data, ...prev]);
                },
            }
        );
        // Cleanup & unsub to stop redis stream
        return () => {
            if (subscription) subscription.unsubscribe();
        };
    }, []);

    // Mark as read function

    // Return Notification component for use on page
    // Generated by ChatGPT since I suck at HTML, will redo to make it match our design
    // Will add loading placeholder html while notifications are loading for user experience
    return (
    <div className="p-4">
      <h1 className="text-2xl font-bold mb-4">My Inbox</h1>
      {notifications.length === 0 ? (
        <p className="text-gray-500">No notifications yet.</p>
      ) : (
        <ul className="space-y-2">
          {notifications.map((n) => (
            <li
              key={n.id}
              className={`p-3 border rounded-lg flex justify-between items-start ${
                n.read ? "bg-gray-100" : "bg-white"
              }`}
            >
              <div>
                <h2 className="font-semibold">{n.title}</h2>
                <p className="text-sm text-gray-600">{n.body}</p>
              </div>
              {!n.read && (
                <button
                  onClick={() => markAsRead(n.id)}
                  className="text-blue-600 text-sm hover:underline"
                >
                  Mark as read
                </button>
              )}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
};

export default Notifications;